version: '3.8'

services:
  node-app:
    container_name: breederpage-node-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:3000"
    volumes:
      # Mount source code but exclude node_modules to avoid overwriting the container's modules
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    restart: unless-stopped