name: deploy
on:
  workflow_dispatch:
env:
  #us-central1-docker.pkg.dev/gen-lang-client-0747690122/vcs-ser3/decoyer/poogle-fe:main
  PROJECT_ID: gen-lang-client-0747690122
  GAR_LOCATION: us-central1
  REPOSITORY: brederpage-demo
  SERVICE: breederpage-demo
  REGION: us-central1
jobs:
  build:
    runs-on: ser3.local.host
    steps:
      - name: Build and push Docker image to registry
        uses: ./.gitea/workflows/build.yaml@main
  deploy:
    needs: build
    runs-on: google-cloud-cli
    steps:
      - name: Google Auth
        id: auth
        uses: 'https://github.com/google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          token_format: 'access_token'
      - name: Deploy to Cloud Run
        id: deploy
        uses: 'https://github.com/google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          # NOTE: You can also set env variables here:
          #  env_vars: |
          #  NODE_ENV=production
          #  TOKEN_EXPIRE=6400

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}